/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudioPrewarmRouteImport } from './routes/audio-prewarm'
import { Route as ApiAudioProxyRouteImport } from './routes/api.audio-proxy'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiReadyRouteImport } from './routes/api.ready'
import { Route as OccurrenceGbifIdRouteImport } from './routes/occurrence.$gbifId'
import { Route as ApiAudioJobsRouteImport } from './routes/api.audio.jobs'
import { Route as ApiBasemapSplatRouteImport } from './routes/api.basemap.$'
import { Route as ApiMapsFilenameRouteImport } from './routes/api.maps.$filename'
import { Route as ApiV1AmbientTracksRouteImport } from './routes/api.v1.ambient-tracks'
import { Route as ApiV1MapRecordsRouteImport } from './routes/api.v1.map-records'
import { Route as ApiV1MetaRouteImport } from './routes/api.v1.meta'
import { Route as ApiMediaIdVariantRouteImport } from './routes/api.media.$id.$variant'
import { Route as ApiV1OccurrencesGbifIdRouteImport } from './routes/api.v1.occurrences.$gbifId'
import { Route as ApiV1CellsResolutionCellIdOccurrencesRouteImport } from './routes/api.v1.cells.$resolution.$cellId.occurrences'
import { Route as ApiV1CellsResolutionCellIdSpeciesRouteImport } from './routes/api.v1.cells.$resolution.$cellId.species'
import { Route as ApiV1CoordinatesLatitudeLongitudeOccurrencesRouteImport } from './routes/api.v1.coordinates.$latitude.$longitude.occurrences'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioPrewarmRoute = AudioPrewarmRouteImport.update({
  id: '/audio-prewarm',
  path: '/audio-prewarm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioProxyRoute = ApiAudioProxyRouteImport.update({
  id: '/api/audio-proxy',
  path: '/api/audio-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: '/api/ready',
  path: '/api/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const OccurrenceGbifIdRoute = OccurrenceGbifIdRouteImport.update({
  id: '/occurrence/$gbifId',
  path: '/occurrence/$gbifId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioJobsRoute = ApiAudioJobsRouteImport.update({
  id: '/api/audio/jobs',
  path: '/api/audio/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBasemapSplatRoute = ApiBasemapSplatRouteImport.update({
  id: '/api/basemap/$',
  path: '/api/basemap/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMapsFilenameRoute = ApiMapsFilenameRouteImport.update({
  id: '/api/maps/$filename',
  path: '/api/maps/$filename',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AmbientTracksRoute = ApiV1AmbientTracksRouteImport.update({
  id: '/api/v1/ambient-tracks',
  path: '/api/v1/ambient-tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MapRecordsRoute = ApiV1MapRecordsRouteImport.update({
  id: '/api/v1/map-records',
  path: '/api/v1/map-records',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MetaRoute = ApiV1MetaRouteImport.update({
  id: '/api/v1/meta',
  path: '/api/v1/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaIdVariantRoute = ApiMediaIdVariantRouteImport.update({
  id: '/api/media/$id/$variant',
  path: '/api/media/$id/$variant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OccurrencesGbifIdRoute = ApiV1OccurrencesGbifIdRouteImport.update({
  id: '/api/v1/occurrences/$gbifId',
  path: '/api/v1/occurrences/$gbifId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CellsResolutionCellIdOccurrencesRoute =
  ApiV1CellsResolutionCellIdOccurrencesRouteImport.update({
    id: '/api/v1/cells/$resolution/$cellId/occurrences',
    path: '/api/v1/cells/$resolution/$cellId/occurrences',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CellsResolutionCellIdSpeciesRoute =
  ApiV1CellsResolutionCellIdSpeciesRouteImport.update({
    id: '/api/v1/cells/$resolution/$cellId/species',
    path: '/api/v1/cells/$resolution/$cellId/species',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiV1CoordinatesLatitudeLongitudeOccurrencesRoute =
  ApiV1CoordinatesLatitudeLongitudeOccurrencesRouteImport.update({
    id: '/api/v1/coordinates/$latitude/$longitude/occurrences',
    path: '/api/v1/coordinates/$latitude/$longitude/occurrences',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-prewarm': typeof AudioPrewarmRoute
  '/api/audio-proxy': typeof ApiAudioProxyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/occurrence/$gbifId': typeof OccurrenceGbifIdRoute
  '/api/audio/jobs': typeof ApiAudioJobsRoute
  '/api/basemap/$': typeof ApiBasemapSplatRoute
  '/api/maps/$filename': typeof ApiMapsFilenameRoute
  '/api/v1/ambient-tracks': typeof ApiV1AmbientTracksRoute
  '/api/v1/map-records': typeof ApiV1MapRecordsRoute
  '/api/v1/meta': typeof ApiV1MetaRoute
  '/api/media/$id/$variant': typeof ApiMediaIdVariantRoute
  '/api/v1/occurrences/$gbifId': typeof ApiV1OccurrencesGbifIdRoute
  '/api/v1/cells/$resolution/$cellId/occurrences': typeof ApiV1CellsResolutionCellIdOccurrencesRoute
  '/api/v1/cells/$resolution/$cellId/species': typeof ApiV1CellsResolutionCellIdSpeciesRoute
  '/api/v1/coordinates/$latitude/$longitude/occurrences': typeof ApiV1CoordinatesLatitudeLongitudeOccurrencesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-prewarm': typeof AudioPrewarmRoute
  '/api/audio-proxy': typeof ApiAudioProxyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/occurrence/$gbifId': typeof OccurrenceGbifIdRoute
  '/api/audio/jobs': typeof ApiAudioJobsRoute
  '/api/basemap/$': typeof ApiBasemapSplatRoute
  '/api/maps/$filename': typeof ApiMapsFilenameRoute
  '/api/v1/ambient-tracks': typeof ApiV1AmbientTracksRoute
  '/api/v1/map-records': typeof ApiV1MapRecordsRoute
  '/api/v1/meta': typeof ApiV1MetaRoute
  '/api/media/$id/$variant': typeof ApiMediaIdVariantRoute
  '/api/v1/occurrences/$gbifId': typeof ApiV1OccurrencesGbifIdRoute
  '/api/v1/cells/$resolution/$cellId/occurrences': typeof ApiV1CellsResolutionCellIdOccurrencesRoute
  '/api/v1/cells/$resolution/$cellId/species': typeof ApiV1CellsResolutionCellIdSpeciesRoute
  '/api/v1/coordinates/$latitude/$longitude/occurrences': typeof ApiV1CoordinatesLatitudeLongitudeOccurrencesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-prewarm': typeof AudioPrewarmRoute
  '/api/audio-proxy': typeof ApiAudioProxyRoute
  '/api/health': typeof ApiHealthRoute
  '/api/ready': typeof ApiReadyRoute
  '/occurrence/$gbifId': typeof OccurrenceGbifIdRoute
  '/api/audio/jobs': typeof ApiAudioJobsRoute
  '/api/basemap/$': typeof ApiBasemapSplatRoute
  '/api/maps/$filename': typeof ApiMapsFilenameRoute
  '/api/v1/ambient-tracks': typeof ApiV1AmbientTracksRoute
  '/api/v1/map-records': typeof ApiV1MapRecordsRoute
  '/api/v1/meta': typeof ApiV1MetaRoute
  '/api/media/$id/$variant': typeof ApiMediaIdVariantRoute
  '/api/v1/occurrences/$gbifId': typeof ApiV1OccurrencesGbifIdRoute
  '/api/v1/cells/$resolution/$cellId/occurrences': typeof ApiV1CellsResolutionCellIdOccurrencesRoute
  '/api/v1/cells/$resolution/$cellId/species': typeof ApiV1CellsResolutionCellIdSpeciesRoute
  '/api/v1/coordinates/$latitude/$longitude/occurrences': typeof ApiV1CoordinatesLatitudeLongitudeOccurrencesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audio-prewarm'
    | '/api/audio-proxy'
    | '/api/health'
    | '/api/ready'
    | '/occurrence/$gbifId'
    | '/api/audio/jobs'
    | '/api/basemap/$'
    | '/api/maps/$filename'
    | '/api/v1/ambient-tracks'
    | '/api/v1/map-records'
    | '/api/v1/meta'
    | '/api/media/$id/$variant'
    | '/api/v1/occurrences/$gbifId'
    | '/api/v1/cells/$resolution/$cellId/occurrences'
    | '/api/v1/cells/$resolution/$cellId/species'
    | '/api/v1/coordinates/$latitude/$longitude/occurrences'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audio-prewarm'
    | '/api/audio-proxy'
    | '/api/health'
    | '/api/ready'
    | '/occurrence/$gbifId'
    | '/api/audio/jobs'
    | '/api/basemap/$'
    | '/api/maps/$filename'
    | '/api/v1/ambient-tracks'
    | '/api/v1/map-records'
    | '/api/v1/meta'
    | '/api/media/$id/$variant'
    | '/api/v1/occurrences/$gbifId'
    | '/api/v1/cells/$resolution/$cellId/occurrences'
    | '/api/v1/cells/$resolution/$cellId/species'
    | '/api/v1/coordinates/$latitude/$longitude/occurrences'
  id:
    | '__root__'
    | '/'
    | '/audio-prewarm'
    | '/api/audio-proxy'
    | '/api/health'
    | '/api/ready'
    | '/occurrence/$gbifId'
    | '/api/audio/jobs'
    | '/api/basemap/$'
    | '/api/maps/$filename'
    | '/api/v1/ambient-tracks'
    | '/api/v1/map-records'
    | '/api/v1/meta'
    | '/api/media/$id/$variant'
    | '/api/v1/occurrences/$gbifId'
    | '/api/v1/cells/$resolution/$cellId/occurrences'
    | '/api/v1/cells/$resolution/$cellId/species'
    | '/api/v1/coordinates/$latitude/$longitude/occurrences'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioPrewarmRoute: typeof AudioPrewarmRoute
  ApiAudioProxyRoute: typeof ApiAudioProxyRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiReadyRoute: typeof ApiReadyRoute
  OccurrenceGbifIdRoute: typeof OccurrenceGbifIdRoute
  ApiAudioJobsRoute: typeof ApiAudioJobsRoute
  ApiBasemapSplatRoute: typeof ApiBasemapSplatRoute
  ApiMapsFilenameRoute: typeof ApiMapsFilenameRoute
  ApiV1AmbientTracksRoute: typeof ApiV1AmbientTracksRoute
  ApiV1MapRecordsRoute: typeof ApiV1MapRecordsRoute
  ApiV1MetaRoute: typeof ApiV1MetaRoute
  ApiMediaIdVariantRoute: typeof ApiMediaIdVariantRoute
  ApiV1OccurrencesGbifIdRoute: typeof ApiV1OccurrencesGbifIdRoute
  ApiV1CellsResolutionCellIdOccurrencesRoute: typeof ApiV1CellsResolutionCellIdOccurrencesRoute
  ApiV1CellsResolutionCellIdSpeciesRoute: typeof ApiV1CellsResolutionCellIdSpeciesRoute
  ApiV1CoordinatesLatitudeLongitudeOccurrencesRoute: typeof ApiV1CoordinatesLatitudeLongitudeOccurrencesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-prewarm': {
      id: '/audio-prewarm'
      path: '/audio-prewarm'
      fullPath: '/audio-prewarm'
      preLoaderRoute: typeof AudioPrewarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio-proxy': {
      id: '/api/audio-proxy'
      path: '/api/audio-proxy'
      fullPath: '/api/audio-proxy'
      preLoaderRoute: typeof ApiAudioProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ready': {
      id: '/api/ready'
      path: '/api/ready'
      fullPath: '/api/ready'
      preLoaderRoute: typeof ApiReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occurrence/$gbifId': {
      id: '/occurrence/$gbifId'
      path: '/occurrence/$gbifId'
      fullPath: '/occurrence/$gbifId'
      preLoaderRoute: typeof OccurrenceGbifIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio/jobs': {
      id: '/api/audio/jobs'
      path: '/api/audio/jobs'
      fullPath: '/api/audio/jobs'
      preLoaderRoute: typeof ApiAudioJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/basemap/$': {
      id: '/api/basemap/$'
      path: '/api/basemap/$'
      fullPath: '/api/basemap/$'
      preLoaderRoute: typeof ApiBasemapSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/maps/$filename': {
      id: '/api/maps/$filename'
      path: '/api/maps/$filename'
      fullPath: '/api/maps/$filename'
      preLoaderRoute: typeof ApiMapsFilenameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ambient-tracks': {
      id: '/api/v1/ambient-tracks'
      path: '/api/v1/ambient-tracks'
      fullPath: '/api/v1/ambient-tracks'
      preLoaderRoute: typeof ApiV1AmbientTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/map-records': {
      id: '/api/v1/map-records'
      path: '/api/v1/map-records'
      fullPath: '/api/v1/map-records'
      preLoaderRoute: typeof ApiV1MapRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/meta': {
      id: '/api/v1/meta'
      path: '/api/v1/meta'
      fullPath: '/api/v1/meta'
      preLoaderRoute: typeof ApiV1MetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/$id/$variant': {
      id: '/api/media/$id/$variant'
      path: '/api/media/$id/$variant'
      fullPath: '/api/media/$id/$variant'
      preLoaderRoute: typeof ApiMediaIdVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/occurrences/$gbifId': {
      id: '/api/v1/occurrences/$gbifId'
      path: '/api/v1/occurrences/$gbifId'
      fullPath: '/api/v1/occurrences/$gbifId'
      preLoaderRoute: typeof ApiV1OccurrencesGbifIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cells/$resolution/$cellId/occurrences': {
      id: '/api/v1/cells/$resolution/$cellId/occurrences'
      path: '/api/v1/cells/$resolution/$cellId/occurrences'
      fullPath: '/api/v1/cells/$resolution/$cellId/occurrences'
      preLoaderRoute: typeof ApiV1CellsResolutionCellIdOccurrencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/cells/$resolution/$cellId/species': {
      id: '/api/v1/cells/$resolution/$cellId/species'
      path: '/api/v1/cells/$resolution/$cellId/species'
      fullPath: '/api/v1/cells/$resolution/$cellId/species'
      preLoaderRoute: typeof ApiV1CellsResolutionCellIdSpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/coordinates/$latitude/$longitude/occurrences': {
      id: '/api/v1/coordinates/$latitude/$longitude/occurrences'
      path: '/api/v1/coordinates/$latitude/$longitude/occurrences'
      fullPath: '/api/v1/coordinates/$latitude/$longitude/occurrences'
      preLoaderRoute: typeof ApiV1CoordinatesLatitudeLongitudeOccurrencesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioPrewarmRoute: AudioPrewarmRoute,
  ApiAudioProxyRoute: ApiAudioProxyRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  OccurrenceGbifIdRoute: OccurrenceGbifIdRoute,
  ApiAudioJobsRoute: ApiAudioJobsRoute,
  ApiBasemapSplatRoute: ApiBasemapSplatRoute,
  ApiMapsFilenameRoute: ApiMapsFilenameRoute,
  ApiV1AmbientTracksRoute: ApiV1AmbientTracksRoute,
  ApiV1MapRecordsRoute: ApiV1MapRecordsRoute,
  ApiV1MetaRoute: ApiV1MetaRoute,
  ApiMediaIdVariantRoute: ApiMediaIdVariantRoute,
  ApiV1OccurrencesGbifIdRoute: ApiV1OccurrencesGbifIdRoute,
  ApiV1CellsResolutionCellIdOccurrencesRoute:
    ApiV1CellsResolutionCellIdOccurrencesRoute,
  ApiV1CellsResolutionCellIdSpeciesRoute:
    ApiV1CellsResolutionCellIdSpeciesRoute,
  ApiV1CoordinatesLatitudeLongitudeOccurrencesRoute:
    ApiV1CoordinatesLatitudeLongitudeOccurrencesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
