ALTER TABLE datasets
  ADD COLUMN IF NOT EXISTS aves_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS insecta_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS audio_occurrence_count BIGINT NOT NULL DEFAULT 0;

-- statement-breakpoint
ALTER TABLE map_cells
  ADD COLUMN IF NOT EXISTS aves_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS insecta_count BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS audio_occurrence_count BIGINT NOT NULL DEFAULT 0;
